homeassistant:
  # Name of the location where Home Assistant is running
  name: Shangri-La
  # Location required to calculate the time the sun rises and sets
  latitude: 48.137154
  longitude: 11.576124
  elevation: 516
  # C for Celsius, F for Fahrenheit
  #temperature_unit: C
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
    
  customize:
    light.domitech_smart_led_retrofit_kit_ze27eu_level_3:
      friendly_name: Hall light  
    sensor.fibaro_system_fgms001_motion_sensor_luminance_2:
      friendly_name: Luminance  
    sensor.fibaro_system_fgms001_motion_sensor_temperature_2:
      friendly_name: Temperature  
    binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_2:
      friendly_name: Motion  
      
# Enables the frontend
frontend:

# Show links to resources in log and frontend
introduction:

# View all events in a logbook
logbook:

# Checks for available updates
updater:

# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# Allows you to issue voice commands from the frontend
conversation:

# Prediction of weather
sensor:
   platform: yr

# Discover some devices automatically
discovery:

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.5/site-packages/libopenzwave-0.3.1-py3.5-linux-armv6l.egg/config

media_player:
  platform: kodi
  host: http://192.168.178.24
  port: 80
  name: Media Player
  user: kodi
  turn_off_action: shutdown

# Group every entity in one single page.
# Different icons can be given for the pages also.
# Groups can be places under groups also.
group: 
  living_room:
    view: yes
    entities:
      - media_player.media_player
      - light.domitech_smart_led_retrofit_kit_ze27eu_level_3
      - sensor.fibaro_system_fgms001_motion_sensor_luminance_2
      - sensor.fibaro_system_fgms001_motion_sensor_temperature_2
      - binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_2
    
automation:
- alias: Turn on living room lights when there is movement
  trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_2
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: 'sensor.fibaro_system_fgms001_motion_sensor_luminance_2'
      below: '100'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_lamp
    

script:
  timed_lamp:
    alias: "Turn on lamp and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_off
      - service: light.turn_on
        data:
          entity_id: light.domitech_smart_led_retrofit_kit_ze27eu_level_3
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_off

  timer_off:
    alias: "Turn off lamp after 5 minutes"
    sequence:
      - delay:
          minutes: 5
      - service: light.turn_off
        data:
          entity_id: light.domitech_smart_led_retrofit_kit_ze27eu_level_3
 
 
# Enable the local mqtt broker
#mqtt:
  #broker: localhost
  #port: 1883
  #client_id: home-assistant-1
  #keepalive: 60
  #username: adithyan
  #password: adithyan
  #protocol: 3.1

#rollershutter:
  #platform: mqtt
  #name: "Bedroom Rollershutter"
  #state_topic: "adithyan/blinds/state"
  #command_topic: "adithyan/blinds/command"
  #qos: 0
  #payload_up: "open"
  #payload_down: "close"
  #payload_stop: "stop"
  #value_template: '{{ value.x }}'
  
#logger:
#  default: debug
  #logs:
    #homeassistant.components.switch.rpi_rf: debug
  
switch:
  platform: command_line
  switches:
    tv:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1135923 1 183"
      command_off: "sudo /home/pi/433Utils/RPi_utils/./codesend 1135932 1 183"
      friendly_name: TV and Speakers
    egg:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1136067 1 183"
      command_off: "sudo /home/pi/433Utils/RPi_utils/./codesend 1136076 1 183"
      friendly_name: Egg boiler
    3:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1136387 1 183"
      command_off: "sudo /home/pi/433Utils/RPi_utils/./codesend 1136396 1 183"
      friendly_name: Unused plug
    grill:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1137923 1 183"
      command_off: "sudo /home/pi/433Utils/RPi_utils/./codesend 1137932 1 183"
      friendly_name: Grill machine
    rice:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1144067 1 183"
      command_off: "sudo /home/pi/433Utils/RPi_utils/./codesend 1144076 1 183"
      friendly_name: Rice cooker


# The stuff for the cooker and other thing coming here.
# {{states.input_slider.fanautooffslider.state}}
         
#input_boolean:
  #fanautooff:
    #name: "Turn Fan Off Automatically"
    #initial: off
    #icon: mdi:fan
