- platform: command_line
  switches:
    tv:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1135923 1 183"
      command_off: "sudo /home/pi/433Utils/RPi_utils/./codesend 1135932 1 183"
      friendly_name: TV and Speakers
    egg:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1136067 1 183"
      command_off: "sudo /home/pi/433Utils/RPi_utils/./codesend 1136076 1 183"
      friendly_name: Egg boiler
    light:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1136387 1 183"
      command_off: "sudo /home/pi/433Utils/RPi_utils/./codesend 1136396 1 183"
      friendly_name: Light
    grill:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1137923 1 183"
      command_off: "sudo /home/pi/433Utils/RPi_utils/./codesend 1137932 1 183"
      friendly_name: Grill machine
    rice:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1144067 1 183"
      command_off: "sudo /home/pi/433Utils/RPi_utils/./codesend 1144076 1 183"
      friendly_name: Rice cooker

- platform: mqtt
  name: "Egg boilerM"
  command_topic: "home/MQTTto433/"
  payload_on: "1136067"
  payload_off: "1136076"
  optimistic: false
  qos: 0
  retain: true

- platform: mqtt
  name: "TV and SpeakersM"
  command_topic: "home/MQTTto433/"
  payload_on: "1135923"
  payload_off: "1135932"
  optimistic: false
  qos: 0
  retain: true

- platform: mqtt
  name: "LightM"
  command_topic: "home/MQTTto433/"
  payload_on: "1136387"
  payload_off: "1136396"
  optimistic: false
  qos: 0
  retain: true

- platform: mqtt
  name: "Grill machineM"
  command_topic: "home/MQTTto433/"
  payload_on: "1137923"
  payload_off: "1137932"
  optimistic: false
  qos: 0
  retain: true

- platform: mqtt
  name: "Rice cookerM"
  command_topic: "home/MQTTto433/"
  payload_on: "1144067"
  payload_off: "1144076"
  optimistic: false
  qos: 0
  retain: true
